spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vietmoney_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: taido231105   # đổi theo máy bạn

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update   # dev dùng update, prod dùng validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: embedded

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: diph.try@gmail.com
    password: "jevn vipf hdlp twgv"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ─── Upload file size (cho scan ảnh) ───────────────────────────────────────
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.vietmoney: DEBUG     # xem log toàn bộ service của mình

app:
  jwt:
    secret: bfd29936c613554dcbdddee5e0158bb4102d45bf59629a8a897d216923e4be8c
    expiration: 86400000

  # ── SỬA: URL đúng của Python FastAPI ──────────────────────────────────────
  # Python chạy port 8001, router prefix là /recognize
  # AiProxyService sẽ gọi: http://localhost:8001/recognize
  ai-service:
    url: "http://localhost:8001"
  gemini:
    api-key:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

  exchange-rate:
    api-url: "https://v6.exchangerate-api.com/v6/611b5efa4b7a9afb5a343b21/latest/VND"

  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:3000